Add checkboxes tests
nirtal85/SeleniumBase-Example pull request #11
Opened 2021-01-02 21:34 UTC by elias-shoursoh

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2021-01-09 14:06 UTC, nirtal85 requested changes

2021-01-09 14:06 UTC, nirtal85 commented on tests/test_checkbox.py
> +        checkbox_list = self.find_elements(CheckBox.checkboxes, By.CSS_SELECTOR)
if css is by defult do we need by.css?

2021-01-15 10:19 UTC, elias-shoursoh commented
Please merge this branch with master.

2021-01-16 12:28 UTC, nirtal85 approved these changes

2021-01-16 12:28 UTC, merged